[package]
name = "rust-car"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libipld = { version = "0.15.0"}
thiserror = "1.0.38"
